import './globals.css';
import localFont from 'next/font/local';
const myFont = localFont({ 
  src: './miniature-display.woff2',
  variable: '--font-miniature-display',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
